---
title: "zxh_demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{zxh_demo}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(alloscore)
```

```{r}
zxh_norm_ex <- zxh_tab2 %>% 
     mutate(
     stdize_news_params(ax = c, a_minus = v, a_plus = h),
     .after = c) %>% as_tibble()

zxh_norm_ex_forecasts <- zxh_norm_ex %>% 
   rename(mean = mu, sd = sigma) %>% 
   add_pdqr_funs(dist = "norm", types = c("p", "q")) %>% 
   mutate(q = map2_dbl(Q, alpha, exec), .after = q_zxh)

allo_norm_ex <- allocate(zxh_norm_ex_forecasts, w = "c", K = 2500, target_names = "Product")
(zxh_norm_ex_allo <- full_join(zxh_norm_ex_forecasts, allo_norm_ex$xdf[[1]], by = "Product") %>% 
  relocate(Opt, allocations))
```

```{r}
allo_norm_ex$xs[[1]] %>% rename(`0` = qs) %>% 
  pivot_longer(
    cols = -Product, 
    names_to = "iteration", 
    values_to = "allocation") %>% 
  mutate(
    iteration = as.numeric(iteration),
    Product = as.factor(as.integer(Product))
    ) %>% 
  ggplot(aes(x = iteration, y = allocation, color = Product)) + 
  geom_line() + geom_point() + theme_classic()
```

```{r}
Zs_norm <- zxh_norm_ex_allo %>% mutate(
  expected_gpl_loss = pmap(., function(F, kappa, alpha, mu, c, ...) {
    exp_gpl_loss_fun(
      F = F,
      kappa = kappa,
      alpha = alpha,
      offset = c*mu)
    })
  ) %>% mutate(
  Z_Opt = map2_dbl(expected_gpl_loss, Opt, exec),
  Z_allo = map2_dbl(expected_gpl_loss, allocations, exec)
) %>% select(Product, c, Opt, allocations, Z_Opt, Z_allo)
```

```{r}
Zs_norm %>% summarise(
  Z_Opt = sum(Z_Opt),
  Z_allo = sum(Z_allo),
  cost_zxh = sum(c*Opt),
  cost_allo= sum(c*allocations)
  ) %>% pivot_longer(everything()) %>%
  as.data.frame()
```

```{r}
zxh_beta_ex <- zxh_tab3 %>% mutate(
     stdize_news_params(ax = c, a_minus = v, a_plus = h),
     .after = c)

zxh_beta_ex_forecasts <- zxh_beta_ex %>% 
   rename(shape1 = Balpha, shape2 = Bbeta) %>% 
   add_pdqr_funs(
     types = c("p", "q"),
     dist = "beta",
     trans = function(x, x_min, x_max) {(x-x_min)/(x_max-x_min)},
     trans_inv = function(q, x_min, x_max) {x_min + (x_max-x_min)*q}) %>% 
   mutate(q = map2_dbl(Q, alpha, exec), .after = q_zxh)

allo_beta_ex <- allocate(zxh_beta_ex_forecasts, w = "c", K = 6500, target_names = "Product")
(zxh_beta_ex_allo <- full_join(zxh_beta_ex_forecasts, allo_beta_ex$xdf[[1]], by = "Product") %>%
  relocate(Opt, allocations))
```

```{r}
allo_beta_ex$xs[[1]] %>% rename(`0` = qs) %>% 
  pivot_longer(
    cols = -Product, 
    names_to = "iteration", 
    values_to = "allocation") %>% 
  mutate(
    iteration = as.numeric(iteration),
    Product = as.factor(as.integer(Product))
    ) %>% 
  ggplot(aes(x = iteration, y = allocation, color = Product)) + 
  geom_line() + geom_point() + theme_classic()
```
```{r}
Zs_beta <- zxh_beta_ex_allo %>% mutate(
  expected_gpl_loss = pmap(., function(F, kappa, alpha, mu, c, ...) {
    exp_gpl_loss_fun(
      F = F,
      kappa = kappa,
      alpha = alpha,
      offset = c*mu)
    })
  ) %>% mutate(
  Z_Opt = map2_dbl(expected_gpl_loss, Opt, exec),
  Z_allo = map2_dbl(expected_gpl_loss, allocations, exec)
) %>% select(Product, c, Opt, allocations, Z_Opt, Z_allo)
```

```{r}
Zs_beta %>% summarise(
  Z_Opt = sum(Z_Opt),
  Z_allo = sum(Z_allo),
  cost_zxh = sum(c*Opt),
  cost_allo= sum(c*allocations)
  ) %>% pivot_longer(everything()) %>%
  as.data.frame()
```
